### ISSUE TITLE
`unique` fails for variables whose first character is not a `valid-id?`

### ISSUE THREAD

**Issue by shawwn** [sctb/lumen#108]
```
> (compile '_*cont*)
"_42cont42"
> (compile '*cont*)
"_42cont42"
> (unique '*cont*)
"_*cont*"
```

Basically, if an identifier's first character isn't a `valid-id?`, then the `id` function prefixes its result with an underscore. But `unique` also prefixes its result with an underscore, resulting in a naming conflict.

One way to solve this is for `unique` to call `compile` on its input:

```
(let (names (obj))
  (define-global unique (x)
    (let x (compile x)
      ...)))
```

This causes compiled identifiers to map to the same bucket as uncompiled ids (e.g. `(unique '*cont*)` and `(unique '_42cont42)`)

```
> (unique '*cont*)
"__42cont42"
> (unique (compile '*cont*))
"__42cont421"
> (unique '_*cont*)
"__42cont422"
```

**Comment by sctb** [comment]
This is definitely a concern, and this solution seems reasonable to try. We can always replace it with something better. Want to open a PR?

**Comment by shawwn** [comment]
On it!

**Comment by shawwn** [comment]
Ah, this will fix reserved words too. Currently:

```
> (compile 'in)
"_in"
> (unique 'in)
"_in"
```

**Comment by shawwn** [comment]
I think this was fixed; will check.

**Comment by sctb** [comment]
Closing as stale.
