### ISSUE TITLE
Lowering does not preserve left-to-right evaluation order

### ISSUE THREAD

**Issue by shawwn** [sctb/lumen#176]
```
> (define-global p (get (require 'system) 'write))
function
> ((fn ())
   (do (p 1)
       (p 2)
       (p 3))
   (p 4)
   (do (p 5) 
       (p 6)))
```

Expected output: `123456`
Actual output: `125346`

Let me know if you'd be interested in a fix.

**Comment by shawwn** [comment]
One reason to reconsider: In traditional lisps, `progn` and `begin` execute each statement in order. The above program written in equivalent Scheme would print out `123456`, for example. 

Lumen's lowering breaks this guarantee. I ran into that when adding Lumen-style lowering to Arc.

**Comment by sctb** [comment]
Yes, that makes sense. We've also done order-preserving lowering elsewhere.
