### ISSUE TITLE
`(define-macro foo () ...)` can't call functions defined in the same file

### ISSUE THREAD

**Issue by laarc** [sctb/lumen#19]
```
> (do (define-global f (x) x)
      (define-macro abc () (f `(list)))
      (abc))
error: f is not defined
```

**Comment by sctb** [comment]
Common Lisp has `EVAL-WHEN` for this, but Lumen does not offer this functionality. The behavior you're requesting is not valid in all cases: it's potentially disastrous to evaluate top-level forms during compilation. The way Lumen itself is compiled is an example of how user functions are intended to be made available to macro definitions.

**Comment by laarc** [comment]
> The behavior you're requesting is not valid in all cases: it's potentially disastrous to evaluate top-level forms during compilation.

In case it's helpful to anyone, here's an example:

```
$ cat << 'EOF' > disaster.l
(define exit () ((if global (get process 'exit) (get os 'exit)))))
(define-macro disaster () (exit))
(define subversive () (disaster))
EOF
```

Any program that attempts to `(compile-file "disaster.l")` will immediately exit.  Worse,

```
(define reader (require 'reader))
(define read-all (get reader 'read-all))
(define stream (get reader 'stream))
(define system (require 'system))
(define read-file (get system 'read-file))

(define read-all-from (path) (read-all (stream (read-file path))))

(print (string (guard (macroexpand (read-all-from "disaster.l")))))
```

would exit without printing anything.  That might seem counterintuitive, since `disaster.l` is merely creating some definitions, not calling any functions.  But `disaster.l` is calling a macro, and of course a macro is just a function that runs at compile time.

There are many reasons why this feature would be a bad idea.  Sandboxing would become more difficult, for example.  It'd still be possible -- the solution is to enter the sandbox before compiling anything, rather than compile something and then sandbox the result -- but that's unexpected and inconvenient.

There's one case where this feature might be helpful:  It enables you to define a helper function which is then used in two or more macro definitions. But that's such a rare case that it seems unlikely.

---

Regardless, no changes to Lumen were ever necessary.  As it turns out, this was never a "feature request."  It's a technique.  In fact, any Lisp implementation that provides `read` and `eval` supports this technique by definition.

If anyone *really* wants to do this, here's how.  (Careful of the aforementioned dangers, though!)

Write a function which reads in your source code using `read-file`, which gives a string.  Then pass the string to `read-all`, which gives a list of expressions.  Then step through the list, calling `eval` on each expression as you go.

So, if you just want to run your code: `(map eval (read-all (read-file "your-program.l")))`

To run-and-compile your code: `(apply cat (map (fn (x) (eval x) (compile x)) (read-all (read-file "your-program.l"))))` and store the result in a .lua or .js file.

To compile your code without running it:  Too bad, you can't!  If your source code calls a macro that calls a function defined in the same file, then there's no way to compile your file without running it.  You'd get an error, since the function doesn't exist.  That's the unfortunate tradeoff in order to get such a powerful and dubious feature.

**Comment by laarc** [comment]
Re-opening.  I've given this some thought.

> The behavior you're requesting is not valid in all cases: it's potentially disastrous to evaluate top-level forms during compilation.

It sounds like you expect that Lumen's `compile-file` function is currently safe.

Consider the following file `foo.l`:

```
(define-macro x ()
  (let (system (require 'system)
        readfile (get system 'read-file))
    (print (cat "Your passwd file is: \n" (readfile "/etc/passwd"))))
  nil)

(x)
```

Run `lumen -c foo.l` and observe that your `/etc/passwd` file is printed.

> Common Lisp has EVAL-WHEN for this, but Lumen does not offer this functionality. 

At the moment, `(define-macro x () y nil) (x)` is equivalent to evaluating `y` during compilation.  So Lumen can be coerced into offering this functionality.

I'm not sure if this is a bug or a feature, but if you were expecting Lumen's users to be able to safely run `lumen -c` on an arbitrary Lumen file without worrying it might be malicious, that's not the case.

In general, if `define-macro` modifies `environment` (i.e. calls `setenv` rather than yields an expression which calls `setenv` when evaluated), it's possible to write a sequence of macros within a single file which causes `lumen -c` to perform arbitrary actions.

It's possible to fix this, but for what it's worth, this functionality is extremely convenient. I found myself needing it again tonight.

Or I'm misunderstanding.  Either way, it seemed best to clarify.

**Comment by sctb** [comment]
> It sounds like you expect that Lumen's compile-file function is currently saf\
e.

Nope. What's important is being able to control what happens at
compile-time. The "disastrous" effects I was referring to would be
breaking the compile-time environment of Lumen, some library, or one's
own program. That is, one can't evaluate *all* toplevel forms
indiscriminately—you would find that Lumen can no longer compile
itself!

Consider this example: if I have a program that I want to compile, and
in it I define a global function called `bind`, evaluating that
toplevel definition at compile-time will break the compiler. So I
either need to a) not do that or b) make it such that doing so does
not break the compiler. At one time in the past Lumen had a module
system that would've prevented this, but there were serious tradeoffs,
so I've gone back to the first option. Another area of concern here is
toplevel variable re-initialization, which some	Lisps handle by
providing a variable type can that avoid that, but Lumen has no such
feature.

The current situation is this: the compile-time environment for each
file being compiled is managed explicitly by providing the code to be
loaded to Lumen at the command-line. This means that by default, macro
definitions cannot reference definitions in the same file.

You've already made the point that I would make here: it's fairly
simple to get the behavior that you want at the form level by defining
something like `EVAL-WHEN` with a macro that calls `EVAL`. That's what
I would recommend you do, although if you have an alternative idea I'd
like to hear it.

**Comment by laarc** [comment]
I see. I'll give it more thought.

From the standpoint of a user, there are two valuable cases to support:

```
(let x val
  (define-macro foo ()
     ; refer to x
   ))
```

```
(define helper ()
   ...)

(define-macro foo ()
  ; call helper
  )
```

I think both can be supported without breaking the compiler, and without resorting to special case logic or surprising behavior.

If I can devise a solution that you feel is clean, simple, consistent, and performant, would you be open to the idea of accepting it into Lumen?

I think I see a way, but it will take some work, which is why I ask.

The solution stems from the fact that if a user writes a macro, whatever they reference within it can use the lexical scope, then the file-level scope, then the global scope. But it's not necessary to evaluate all toplevel forms just to use function definitions within the file-level scope.

File-level variable definitions (local/global, not lexical) shouldn't be evaluated at compile time. They are likely to be initialized to a value which is only valid at runtime.

But function defs are different. They're a description of what should happen when they're called. Such descriptions can be made available to be used immediately, and it's up to the user whether to choose to use them within a macro.

The shadowing problem you mention has a logical solution: a `require` statement shouldn't be evaluated by the compiler either. Therefore the only case that would break the compiler is if the user defined a function named `bind`, which shadowed the global `bind`. But (a) that would only break that one file, and (b) once the new changes are in place, `bind` can be made a local function which the compiler module closes over.

This is partly speculation, but my feeling is that I can do it, if you're interested. If there are ways to reduce the number of special cases the user has to worry about (like `EVAL-WHEN`), it may be worthwhile to try.

It's admittedly not a big deal either way. And as I write this, I realize that whatever I change, it will cause Lumen to be slightly slower, even if marginally. This idea should probably be rejected on that basis alone, since Lumen is so powerful partly because it's so effecient. Quantifying how much slower Lumen would become may be worthwhile, however. It's up to you.

**Comment by sctb** [comment]
> If I can devise a solution that you feel is clean, simple, consistent, and performant, would you be open to the idea of accepting it into Lumen?

Yes, but the bar will be high :)

I'm skeptical that this is worth the trouble, especially since the 
precedent for the current behavior has been established by
something as thoughtful as Common Lisp. However, if you want
to see what you can come up with it's fine for me. Bail if you 
find yourself writing a module system, though.

**Comment by laarc** [comment]
As expected, Lumen's compilation speed was slowed by 4% to 10%.  Bailing.
