### ISSUE TITLE
On Lua hosts, a fn created via `define` cannot be called at any point above the definition

### ISSUE THREAD

**Issue by laarc** [sctb/lumen#20]
Lua gets an error:

```
$ LUMEN_HOST=luajit bin/lumen -e "(do (define-global f (x) (g x)) (define g (x) (+ x 1)) (f 21))"
error: attempt to call global 'g' (a nil value)
```

Node works as expected:

```
$ LUMEN_HOST=node bin/lumen -e "(do (define-global f (x) (g x)) (define g (x) (+ x 1)) (f 21))"
22
```

There might not be an easy fix for this, but it'd be very nice.  For example PR #17 had to move the definition of `run` to the top of the file in order for the `remap` function to call it.

The `ac.l` file I'm writing should look as visually similar to 3.1's `ac.scm` as possible.  But the very first definition in `ac.scm` is the `ac` function, which then calls a bunch of functions that are defined later in the file.

Without this feature, I'm currently forced to use `define-global` for all functions in my `ac.l` file.

(To be clear, this isn't a very important issue. I'm fine with using `define-global` for everything.  I figured I'd mention it though.)

**Comment by sctb** [comment]
I decided to leave this behavior up to the host implementation. Lua happens to be quite a bit stricter about its definitions (this also comes up in recursive definitions).
