### ISSUE TITLE
embedding

### ISSUE THREAD

**Issue by velkyel** [sctb/lumen#212]
I'd like to embed lumen into my game/demo engine which already contains lua (binding to c/c++ is done through sol2).  Anyway I'm not sure how to do it correctly.  My plan is to embed compiled compiler.lua, reader.lua and system.lua.    Calling reader.read_string(str) function where str is incoming "remote" string containing lisp form I get input to compiler.eval()?  Or there is another step needed?

**Comment by sctb** [comment]
That sounds right to me! You can use the code for the [REPL](https://github.com/sctb/lumen/blob/master/main.l#L16) as a reference.

**Comment by shawwn** [comment]
If you have additional questions, feel free to hop into Slack: https://join.slack.com/t/lumen-language/shared_invite/enQtNDczMjI1MjQ0ODk5LWI3OTdiMTIwNTgwZjgwOGFlYTA2MTZhMzAzZTgxMjZkMjJmN2MwYjdiZjU1M2Q5NjE5ZDAyNDljOWFkYTZhMDg

Or Discord: https://discord.gg/qaqkc9z

I can walk you through embedding Lumen and setting up some bindings.
