### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by lsx7** [sctb/lumen#217]
Hi guys,

First I have to say that I'm very impressed by this project, I've seen it mentioned a few times on HN and I'm surprised that it has very little adoption.

What's the overall status of Lumen? Is it ready to be used in real projects?

**Comment by sctb** [comment]
Thank you for the kind words! The project isn't really active, though you might still get some mileage out of it. Bug reports and patches still welcome. ☺️

**Comment by lsx7** [comment]
Thank you for your answer. Basically, what I'm looking for is a self-hosted alternative to Parenscript and Lumen seems to the closest thing that I found.

My main concern is debugging - from what I can tell, there's no support for source maps and even with interpreting the code directly with "bin/lumen", line numbers in stack traces were not accurate in a few simple tests that I've done. Do you have any tips on that?

**Comment by sctb** [comment]
Sorry, there is pretty much no debugging support! For what it's worth I've just used a JavaScript debugger on the generated output if necessary.
