### ISSUE TITLE
Can't use "var" as the name of a fn arg when LUMEN_HOST=node

### ISSUE THREAD

**Issue by laarc** [sctb/lumen#24]
To reproduce:

```
$ LUMEN_HOST=node bin/lumen -e '(fn (var) var)'
error: Unexpected token var
```

Expected behavior:

```
$ LUMEN_HOST=node bin/lumen -e '(fn (x) x)'
function
```

I run into this pretty frequently since "var" is a descriptive name.  I usually try to use it as the name of a macro argument, then remember it doesn't work on Node.

Which part of the compiler do you think would need to be changed to allow "var" to be used like that?

Thanks for your time.

**Comment by laarc** [comment]
The issue is that you can't use a reserved word as the name of a variable.  Specifically, any of these:

```
(define reserved
  (set-of "=" "==" "+" "-" "%" "*" "/" "<" ">" "<=" ">="
          ;; js
          "break" "case" "catch" "continue" "debugger"
          "default" "delete" "do" "else" "finally" "for"
          "function" "if" "in" "instanceof" "new" "return"
          "switch" "this" "throw" "try" "typeof" "var"
          "void" "with"
          ;; lua
          "and" "end" "in" "repeat" "while" "break" "false"
          "local" "return" "do" "for" "nil" "then" "else"
          "function" "not" "true" "elseif" "if" "or" "until"))
```

The reason is pretty obvious.  It'd be like trying to use "return" as the name of a variable:

```
$ LUMEN_HOST=node bin/lumen -e "(print (compile ((get (require 'compiler) 'expand) '(fn (return) return))))"
function (return) {
  return(return);
}
```

Obviously bogus. 

The trouble is, some of those reserved names are very good.  It depends on what kind of program the user is writing.  `end` and `in` might be excellent names for functions or macros.  `var` is an excellent name for a macro arg.  So it might be good to let Lumen users use reserved words as names, if possible.  But is it?

The current situation is a bit counterintuitive.  Here are a few illustrations:

---

You can write code that works on one host but breaks on the other.  For example, you can't use a reserved word as the name of a global function.

```
$ LUMEN_HOST=lua bin/lumen -e "(do (define-global var (x) x) (var 21))"
21
```

```
$ LUMEN_HOST=node bin/lumen -e "(do (define-global var (x) x) (var 21))"
error: Unexpected token =
```

```
$ LUMEN_HOST=node bin/lumen -e '(do (define-global end () `ok) (end))'
"ok"
```

```
$ LUMEN_HOST=lua bin/lumen -e '(do (define-global end () `ok) (end))'
error: [string "function end()..."]:1: <name> expected near 'end' in function end()
  return("ok")
end
_37result = end()
```

---

Amusingly, it's perfectly fine to use a reserved word as the name of a macro.

```
$ LUMEN_HOST=node bin/lumen -e '(do (define-macro var (name val) `(define ,name ,val)) (var x 21) x)'
21
```

```
$ LUMEN_HOST=lua bin/lumen -e '(do (define-macro end () ``ok) (end))'
"ok"
```

---

But you can't use a reserved word as the name of a macro argument.

```
$ LUMEN_HOST=node bin/lumen -e '(do (define-macro when-nil (var rest: body) `(when (nil? ,var) ,@body)) (let x nil (when-nil x "x is nil")))'
error: Unexpected token var
```

```
$ LUMEN_HOST=lua bin/lumen -e '(do (define-macro when-nil (var rest: body) `(when (nil? ,var) ,@body)) (let x nil (when-nil x "x is nil")))'
"x is nil"
```

---

Maybe irrelevant, but probably worth mentioning:  As Lumen becomes popular, it will become difficult to add additional targets to Lumen without breaking existing code.  For example, any Lumen code that uses "interface" as a variable name will break if Lumen adds a Go target.

---

What do you think?  I don't know whether anything should be changed.  Maybe every Lumen programmer will just have to keep these corner cases in mind.

On the other hand, the problem of "Is it possible to use reserved words as variable names?" seems very similar to "Is it possible to use reserved characters like `?` or `!` in variable names?" which Lumen solves.  Perhaps there's a similar solution for this.

**Comment by sctb** [comment]
You've come across a TODO that I've had for a little while! Try all of these examples with `LET`, they ought to work. `LET` rewrites reserved names, which should be done for function parameters but isn't. There will be a bit of trickiness to get it right, but it should be doable.

**Comment by sctb** [comment]
Function names are probably a different story, though, since they're the sort of "ABI" of the host environment. I expect there will always be a bit of host-dependent behavior there.

**Comment by laarc** [comment]
This seems to work:

![image](https://cloud.githubusercontent.com/assets/13237912/11101168/5011ebce-886a-11e5-97c0-56845f2051ff.png)

"If the compiled version of an identifier is `reserved?` then prefix it with an underscore."

(The reason for the ugly `(or (= id1 "_") ...` is because dashes in identifiers are converted into underscores, so `reserved?` won't work for reserved words that contain dashes.  But `-` is the only reserved word containing a dash, and `_` is the result of compiling `-`.)

These work now:

```
$ LUMEN_HOST=node bin/lumen -e '(do (define var (var) var) (var 21))'
21
```

```
$ LUMEN_HOST=lua bin/lumen -e '(do (define in (continue else) (list else continue)) (in 7 42))'
(42 7)
```

```
$ LUMEN_HOST=node bin/lumen -e '(do (define in (continue else) (list else continue)) (in 7 42))'
(42 7)
```

Certain reserved words still can't be used, such as infix operators, `while`, `return`, `case`, `do`, `nil`, etc.  Those are macros or special forms.  But that seems ok since this frees up most of the reserved words that people will want to use in practice.

I fully recompiled Lumen using `LUMEN_HOST=node`, then ran all tests.  I repeated the process for `lua` and `luajit` hosts.  Everything seems to work.  But I've learned to be very cautious with changes like this.

Do you think this a bad idea in principle?

Thanks again.

**Comment by sctb** [comment]
Two thoughts:

1. If we did this in `id`, I would first check `reserved?` (and `-`), then add the leading underscore, otherwise process the identifier character-by-character
2. This *should* mean that we could get rid of the call to `reserved?` in the definition of `let`. Can you try that?

If it works, I'd say go ahead with this change.
