### ISSUE TITLE
Multiline raw string syntax

### ISSUE THREAD

**Issue by laarc** [sctb/lumen#29]
```
> """a
b
c"""
"a\nb\nc"
```

```
> ||
a
b
c
d
||
"\na\nb\nc\nd\n"

**Comment by sctb** [comment]
The standard string reader supports multiple lines.
```
$ lumen
> (define a "
can you do this?
I think so")
> a
"\ncan you do this?\nI think so"
```

**Comment by laarc** [comment]
Sorry.  Let me try this again.

Open `compiler.l` in emacs.  Highlight a few pages of code, and copy it to your clipboard.

Open lumen.  Try to paste that code into a Lumen string.  You'll find it very difficult, I think.  If your code contains a `"` character, `" ... paste here ... "` will break.  Or if it contains the sequence `\n`.

For example, copy all of the following code to your clipboard:

```
(patch "reader.l"
||
(define-reader ("\"" s)
  (read-char s)
||
||
(define-reader ("\"\"\"" s)
  (read-char s 3)
  (with r nil
    (let str "\""
      (while (nil? r)
        (let c (peek-char s 3)
          (if (= c "\"\"\"") (set r (cat str (do (read-char s 3) "\"")))
              (nil? c) (set r (expected s "\"\"\""))
            (let x (read-char s)
              (cat! str (if (or (= x "\"") (= x "\\")) (cat "\\" x) x)))))))))

(define-reader ("\"" s)
  (when (= (peek-char s 3) "\"\"\"")
    (return ((get read-table "\"\"\"") s)))
  (read-char s)
||)
```

Then open lumen and try to create a Lumen string equal to the contents of your system clipboard.

There's no way to do that right now.  `(inner '|   ... paste here ... |)` is as close as you can get.  But if you try to paste anything containing a pipe `|` character, like the above example, then that won't work either.

Using `""" ... paste here ... """` works:

![image](https://cloud.githubusercontent.com/assets/13237912/11416958/5ce5eb12-93c7-11e5-86c4-80113e7bad74.png)

The title of this issue was a misnomer.  The issue is about raw string syntax, not multiline string syntax.

In Python, you can turn off backslash substitution by prefixing a string literal with `r`. 

```py
r"foo \n bar"
```

gives `"foo \\n bar"` -- it doesn't contain a newline character.

```py
r"""foo \n bar"""
```

gives the same thing.

It's common to want to turn off backslash substitution.  If someone wants to create a string containing a regex, then they'll find it difficult.

I propose Lumen should have some way of being able to store a complex, ugly regex into a Lumen string.   I.e. some way of turning off backslash substitution + some syntax other than `"` so that quote chars don't need to be escaped with backslashes.

**Comment by sctb** [comment]
Got it! I'll give it some thought.

**Comment by laarc** [comment]
`~~` is quite pretty:

```
(patch "reader.l"
~~
(define-reader ("\"" s)
  (read-char s)
~~
~~
(define-reader ("\"\"\"" s)
  (read-char s 3)
  (with r nil
    (let str "\""
      (while (nil? r)
        (let c (peek-char s 3)
          (if (= c "\"\"\"") (set r (cat str (do (read-char s 3) "\"")))
              (nil? c) (set r (expected s "\"\"\""))
            (let x (read-char s)
              (cat! str (if (or (= x "\"") (= x "\\")) (cat "\\" x) x)))))))))

(define-reader ("\"" s)
  (when (= (peek-char s 3) "\"\"\"")
    (return ((get read-table "\"\"\"") s)))
  (read-char s)
~~)
```


The trick, I think, is to choose a tasteful but uncommon sequence of characters.  Lumen is pretty much a metalanguage.  I suspect that in the future, many users are going to process various other languages in Lumen.  So if we choose a short, uncommon sequence of chars, users won't have any trouble pasting in whatever they want.

Here's the other trick.  Let's say that we use `~~foo \n bar~~` as the syntax to create `"foo \\n bar"`.  Now let's say that you want to create a string equal to `"\"~~foo \\n bar~~\""`.  How would you do it?

There's no way to use `~~` to create a string containing `~~`.  So if the syntax is `~~`, there would need to be some way to handle this, or users will run into it.

Same for `"""`.  If the syntax is `"""`, users won't be able to paste in Python, since Python uses `"""` within the language..  Same for `||` for Javascript.

The solution I use in laarc is to provide two different syntaxes.  By providing both `"""` and `||`, users can switch between them whenever they need to.

I think `"""` and `||` are ugly, though.  `::` and `~~` seem a little better.

But it smells like there's a better, simpler design lurking in the shadows.  I don't think any of my ideas are very good.  While I tolerate a small number of hacks in laarc, I don't think Lumen should suffer from any decision that might be described as hacky.  Both `"""` and `||` seem like hacks.  But I don't know.  `|foo bar|` is already pretty common in the lisp world, so `||foo bar||` seemed like a natural way to handle multiline raw strings.

**Comment by laarc** [comment]
I think motor is the target to aim for.

```
;; -*- mode: lisp -*-

(define ffi (require 'ffi))
(define buffer (require 'buffer))

(define-c ffi |
int socket(int domain, int type, int protocol);
int fcntl(int fildes, int cmd, ...);

typedef int socklen_t;

int bind(
  int socket,
  const struct sockaddr *address,
  socklen_t address_len);

int listen(int socket, int backlog);

int accept(
  int socket,
  struct sockaddr *restrict address,
  socklen_t *restrict address_len);

int setsockopt(
  int socket,
  int level,
  int option_name,
  const void *option_value,
  socklen_t option_len);

typedef uint8_t sa_family_t;
typedef uint16_t in_port_t;
typedef uint32_t in_addr_t;

struct in_addr {
  in_addr_t     s_addr;
};

uint16_t htons(uint16_t hostshort);
uint32_t htonl(uint32_t hostlong);

typedef unsigned int nfds_t;

struct pollfd {
  int   fd;
  short events;
  short revents;
};

int poll(struct pollfd *fds, nfds_t nfds, int timeout);
int close(int fildes);

char *strerror(int errnum);

typedef unsigned int size_t;
typedef int ssize_t;

ssize_t read(int fildes, void *buf, size_t nbyte);
ssize_t write(int fildes, const void *buf, size_t nbyte);
|)

(require 'system)
...
```

It's strikingly beautiful.  Coming across `motor.l` was one of the things that originally captured me and turned me into a Lumen user.

In that light, the design problem to focus on is:  `define-c` is a macro, and not a function.  It has to be, in order to write `motor.l` that way.   When you call `(define-c ffi | ... code ... |)`, it expands the pipes into `(inner '| ... code ... |)`.

And that's fine.  It works.  But the fact that `define-c` *has* to be a macro to accomplish that is worrying.  When you do `(define-c ffi | ... code ... |)`, that is conceptually an *operation*, not a syntax.  `define-c` is conceptually a function in the same way `sort` is conceptually a function: you should be able to pass `define-c` as an argument to some utility, not merely call it in source code.

Worse, there's no way for `define-c` to be passed any C code with a `|` character.  Luckily it doesn't need to, since C defs never use `|`.  But when I wrote a similar type of program (monki) -- "here is some code, do something with it", just like motor --  I needed to be able to paste in pipe characters.

As I wrote monki, I was worried that I kept having to make all the functions into macros just to support motor's `|foo|` syntax.  `(patch "reader.l" |x| |y|)`, for example.  Monki's `patch` function *has* to be a macro for the same reason `define-c` had to be.  But I slogged through it because of how pretty it is.

What stopped me cold was when I needed to write some code like `(patch "foo.js" |if (foo || bar)| |if (bar || foo)|)`.  Lumen's reader doesn't allow you to create an `id-literal` that contains pipe chars.  So that breaks.

Good, I say.  Lumen's reader should stay that way.  It would be very ugly to worry about escaping pipe chars with backslashes.  I don't want to live in a future where I'd express that as `(patch "foo.js" |if (foo \|\| bar)| ...`.

--

So here's something to consider:  Right now, lumen doesn't use `id-literal`s very much.  In fact, there are only a handful of instances of pipe characters anywhere within lumen:

![image](https://cloud.githubusercontent.com/assets/13237912/11431265/05c6b41a-9449-11e5-82b7-5ef919231d65.png)


Using a pipe character as a syntax is extremely valuable.  If it's a syntax, you might want it to mean something that gives you a lot of bang for the buck it represents. The current situation is that `|foo|` generates an `id-literal`.  This might not be very ideal, going forward.

The fact that `id-literal`s are so uncommon in real code means that an `id-literal` shouldn't get to "take up" such a precious syntax like`|foo|`.  It should be something else. I don't know what.  All I know is that `|foo|` is so valuable, you should really consider making it the way to make multiline raw strings.  Since I appear to be the first user, it might be okay to change the meaning of `|foo|`.  A few years down the line, you might not be able to make decisions like that without affecting a bunch of existing users.   I'm pretty certain lumen's popularity is about to explode, especially once I start showing the world what it can do.

I propose `|foo|` and `||foo||` should both mean the same thing:  "here is a raw string. no backslash substitution will be performed".  So `|foo\nbar|` and `||foo\nbar||` should both yield `"foo\\nbar"`.

If you do that, and you also let `||foo||` mean the same thing as `|foo|`, that completely solves the issue.  It "feels" like the right answer.  Whenever any user wants to paste some code into their Lumen program, they can just paste it like `| ... paste here ... |`.  Even if they paste in something like this:

```
(process-javascript |

function example (x) {
  return x || "example";
}

|)
```

... that will work fine.  Lumen's reader will not terminate the string until it runs across a pipe followed by not-pipe.  So when it runs into the pipe in `x || "example"`, it goes "Ah, there's more than one pipe, so keep going."


But what if they want to paste in some code like this?

```
(process-javascript |

function example2 (x) {
  return x | 0;
}

|)
```

That will break.  That's why I'm saying `||foo||` should mean the same thing as `|foo|`.  Because at that point, users can just write it like

```
(process-javascript ||

function example2 (x) {
  return x | 0;
}

||)
```

And that will work perfectly, because Lumen's reader won't terminate until it runs into `||`.  So users can just switch back and forth as-needed.  It's consistent, it handles almost every real-world case, and it's beautiful.  I want it.  I must have it!  I'll send you ten pizzas as a bribe.

At that point, `define-c` can be turned into what it should be: a function, not a macro.  And monki can be written to use functions instead of macros.  It seems to make sense.  But if I'm overlooking something, just toss out this idea.

The only question is how to express an `id-literal`.  If `|foo|` becomes a string, not an `id-literal`, what syntax should an id-literal use?

I don't know.  All I know is that motor is so pretty.  `|x|` should yield a string, not an id-literal.

It might sound like I'm really attached to this idea, but in reality I don't mind if you reject it.  If all of this is a bad idea then just toss it out and let me know why.

One thing that we should *not* do, however, is make `[[foo]]` be the syntax.  Nor `{{foo}}`.  In arc, `[+ _ 1]` expands into `(fn (_) (+ _ 1))`.  And `[[+ _ 1] 2]` is completely valid.  Since I'm trying to make laarc support all of arc3.1, if you make `[[foo]]` be the syntax for a multiline string, that will break arc's shorthand.

Let me know what direction you think is best.

You're a machine, though.  I don't know how you juggle all of the things you work on.  You have so much other stuff to do and to think about than these types of issues. Feel free to put this on the backburner for as long as you want, if you need to.

Whenever I launch a wall of text at you, I go back through it and try to make sure I'm saying something valuable, and saying it clearly.  I just hope all of this is as fun for you as it is for me!
