### ISSUE TITLE
Should "." expand to "rest:"?

### ISSUE THREAD

**Issue by laarc** [sctb/lumen#30]
In laarc, I've modified `reader.l` to replace `.` with `rest:` which enables functions to be written like

```
> ((fn (x . ys) ys) 1 2 3)
(2 3)
```

I have no idea whether this would be a good feature for Lumen or not, but I thought I'd mention it in case it's helpful.

Pros: Easier to read.

Cons:  It conceals how Lumen works, so maybe it's too confusing.

Here's how I do it:

```
; reader.l: turn "." atoms into "rest:" atoms.
; This enables (fn (x . ys) ...) rather than (fn (x rest: ys) ...)
(patch "reader.l"
||
        (= str "-inf") -inf
||
||
        (= str "-inf") -inf
        (= str ".")    "rest:"
||)
```

---

Aside: it turns out that you can't add this feature using `(setenv "." symbol: "rest:")` because the reader doesn't check for defined symbols as it reads, so I had to modify the reader itself.  Do you think it might be a good feature for Lumen's reader to pay attention to the environment's symbols somehow?  I'm not sure that makes sense, but if you have any thoughts on how it could work, let me know.

**Comment by sctb** [comment]
A nice convenience feature, but misleading to Lispers.

> Do you think it might be a good feature for Lumen's reader to pay attention to the environment's symbols somehow?

I don't think so, no.
