### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by laarc** [sctb/lumen#34]
https://github.com/sctb/lumen/wiki redirects to https://github.com/sctb/lumen

Some sort of wiki might be important.  Want to change the project settings to make https://github.com/sctb/lumen/wiki available?

It's a pretty big commitment, though.  Maybe I should create an unofficial wiki elsewhere, which the project links to?

FWIW, I'm volunteering to maintain the wiki.  But if I get hit by a bus, suddenly you'll have a wiki to worry about.  So it's up to you.

**Comment by laarc** [comment]
Outline of planned wiki content:

----
- Benchmark comparisons

----
- Examples of projects built with Lumen

----
- Quickstart: a "hello, world" console app; how to deploy it to npm

----
- Tutorial: Writing a webserver using Node's http module; how to deploy using Heroku

----
- Troubleshooting: Illustrate various common (but unexpected) corner cases I've run into, show why they happen

----
- Contribution guidelines:  What's expected of a pull request.
- "Run this script which rebuilds Lumen 3 times on all three hosts,"
-  maybe some tooling to measure performance regressions introduced by the PR.

----
- Community: 
- Where to seek help
- (chatrooms,  mailing lists)

----
- Current work that would be valuable to do
- Documentation, walkthroughs
- Translate the Computer Language Benchmarks Game benchmarks into Lumen equivalents

----
- Some commentary about working with "foreign" code
- How to import an npm module
- How to use luajit to interface with C
- How to work with luvit

**Comment by sctb** [comment]
This sounds like a good idea for an unofficial (for now) wiki.
