### ISSUE TITLE
The 'string' function conflicts with 3rd party lua libraries

### ISSUE THREAD

**Issue by laarc** [sctb/lumen#35]
Lua libraries sometimes do `string = require("string")`, which causes Lumen runtime functions that depend on Lumen's `string` function to break.

I ran into this when I tried adding support for `LUMEN_HOST=luvit`, which is a highly useful lua framework that essentially implements Node-style APIs, such as the http module.

I decided to open and then close this issue, because I don't know if future Lumen users will run into this. maybe it's luvit-specific.  If that's the case, I can work around it.

But since Lua's standard module is named 'string', we may want to use a different name, like 'make-string'.

**Comment by laarc** [comment]
The problem is that `(define-global string ...` prevents 3rd party Lua libraries from calling e.g. `string.match`:

Reopening -- It's not really possible to use 3rd party Lua libs, since most of them call some kind of `string.foo` function.  I ran into this when trying to use [ufo](https://github.com/malkia/ufo) which otherwise works.

Which name do you feel Lumen should use for the `string` function?

**Comment by laarc** [comment]
To clarify, after cloning ufo, their samples can't be run in Lumen due to the naming conflict:

```
> (compiler.run (read-file "samples/notch.lua"))
error: attempt to index global 'string' (a function value)
stack traceback:
   ...
```

**Comment by sctb** [comment]
Yes, agreed. I'll rename our `string`.

**Comment by laarc** [comment]
Works great.  Thought you might enjoy seeing this Lumen demo:

http://gfycat.com/FlawlessAfraidCanvasback

(It's 10 seconds long.)

It's a bit unfair to say "It's a Lumen demo," since it's using ufo's standard "notch.lua" sample.

But this is the first Lisp I'm aware of that can interface with so many 3rd party libraries.  Every Lumen user has all of Node and all of Lua at their disposal, and this is proof. 

Nothing special was required to run this demo.  This is simply what Lumen can do now.
