### ISSUE TITLE
Proposal: Should support for standard lua be dropped?

### ISSUE THREAD

**Issue by laarc** [sctb/lumen#6]
I'm now taking on the task of writing my own lumen library, using sctb/motor as a guide.  I noticed that motor relies on LuaJIT's ffi library:

```
(define-macro define-c (v x)
  (cat "|" v ".cdef[[" (inner x) "]]|"))
```

It may be possible for standard lua to run motor using a shim like https://github.com/jmckaskill/luaffi

But it might be better to drop lua support altogether.  Here some pros and cons.

Pros:

- As Lumen gains popularity, people will certainly want to write libraries similar to motor.  Interfacing with other C libraries might even be the most common thing people will want to do with Lumen.  If we drop lua, we can move motor's ffi support into lumen.  Of course, `node` won't support these ffi semantics, but that seems fine.  The gain in convenience seems worth the disparity.  Plus it might be possible to write a C declaration parser / ffi shim that implements LuaJIT's ffi semantics on `LUA_HOST=node`.

- LuaJIT has attained widespread adoption, e.g.:
  - Torch is a popular LuaJIT scientific computing framework:  http://torch.ch/ 
  - The gamedev industry usually embeds LuaJIT rather than Lua.  LuaJIT is API-compatible with Lua 5.1, which made it a drop-in replacement for engines that embedded standard Lua.  (An interesting case study in how to subvert an entrenched competitor...)
  - LuaRocks is a popular Lua packaging system, similar to pip and rubygems.  It was originally for standard lua, but now it appears to work with LuaJIT:  https://github.com/torch/luajit-rocks

- On my machine, fully recompiling Lumen takes 1.25sec using LuaJIT vs 3.35sec using Lua, though this benchmark probably doesn't matter.  (Making a `bench.l` benchmark suite is on my todo list.)

Cons:

- There are some interesting (if overstated) points in http://stackoverflow.com/questions/24230195/regular-lua-interpreter-vs-luajit-interpreter
  - PUC Lua (the "normal interpreter") is more stable, i.e. bugs are more frequently found in LuaJIT.
  - PUC Lua is smaller, i.e. it takes less memory.
  - PUC Lua is much easier to understand if you want to customize it.
  - PUC Lua has been ported to way more platforms and is easier to port.
  - LuaJIT does not support all of Lua 5.2 features yet.
    -  On the other hand, LuaJIT seems to support most of the important Lua 5.2 features.

**Comment by sctb** [comment]
I envision Lumen proper to be as general and small as possible, and would rather that platform-specific concerns be dealt with by other libraries (motor is an incomplete example). Even now there are functions in `runtime.l` that support the compilation driver that I feel don't belong, e.g. `write-file`. I would like Lumen to target languages (JavaScript, Lua) and be as portable as possible across implementations (Node, browsers, PUC, LuaJIT).

The way to make Lumen practical is to have libraries that implement platform-specific functionality, and to  make Lumen itself extensible to support this. The reader and the compiler are designed with that in mind: libraries and programs are welcome to add syntax or special forms for custom compiler output.

**Comment by laarc** [comment]
Ah, good points!  Thanks.
